version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "Marines@MQ"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vfxJjv8RktyBEEs
    volumes:
      - ./mysql-data:/var/lib/mysql
  que:
    image: docker.cloudloom.io/que-enterprise:0.0.5
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: -Xmx16g -Xms4g
    links:
      - mysql
